<?php
echo "Test<br>";
if ($_SERVER["REQUEST_METHOD"] == "POST") {
  // retrieve form data
  $name = $_POST["username"];
  $email = $_POST["Contact"];
  $message = $_POST["DonationMessage"];
  $money = $_POST["DonationAmount"];

  echo "Username: ", $name, "<br>email: ", $email, "<br>Your message: ", $message, "<br>The donation: ", $money;
  // connect to database
  $servername = "blsmrubaitx9fvhabofr-mysql.services.clever-cloud.com";/*I am using a free database hosting service at clever cloud. It's really neat */
  $username = "uqpbtptfdrqz5j8i";
  $password = "62yBaSXGnGrmGUzMV1zb";
  $dbname = "blsmrubaitx9fvhabofr";

  $conn = new mysqli($servername, $username, $password, $dbname);

  // check connection
  if ($conn->connect_error) {
    echo ("Connection failed: " . $conn->connect_error);
    die("Connection failed: " . $conn->connect_error);
  }

  echo "<br>still works";

  // prepare SQL statement
  $stmt = $conn->prepare("INSERT INTO Donation (username, contact, DonationMessage, DonationAmount) VALUES (?, ?, ?, ?)");
  $stmt->bind_param("ssss", $name, $email, $message, $money);

  // execute statement
  if ($stmt->execute()) {
    // redirect to thank-you page
    header("Location: ../thankyou.html");
    exit;
  } else {
    // handle error
    echo "Error: " . $stmt->error;
  }

  // close database connection
  $stmt->close();
  $conn->close();
}
?>
<!--The code was generated by ChatGPT, and tweaked by me, so that it would work in the context-->