<!--This is currently unused, due to databases being weird.-->

<?php
// connect to database
$servername = "blsmrubaitx9fvhabofr-mysql.services.clever-cloud.com";/*I am using a free database hosting service at clever cloud. It's really neat */
$username = "uqpbtptfdrqz5j8i";
$password = "62yBaSXGnGrmGUzMV1zb";
$dbname = "blsmrubaitx9fvhabofr";

$conn = new mysqli($servername, $username, $password, $dbname);

// check connection
if ($conn->connect_error) {
  die("Connection failed: " . $conn->connect_error);
}

// prepare SQL statement
$stmt = $conn->prepare("SELECT username, donationAmount, donationMessage FROM Donation ORDER BY donationAmount DESC");

// execute statement
$stmt->execute();

// bind result variables
$stmt->bind_result($username, $donationAmount, $donationMessage);

// build table
echo "<table>";
echo "<tr><th>Username</th><th>Donation Amount</th><th>Donation Message</th></tr>";
while ($stmt->fetch()) {
  echo "<tr><td>$username</td><td>$donationAmount</td><td>$donationMessage</td></tr>";
}
echo "</table>";

// close database connection
$stmt->close();
$conn->close();
?>

<!--This code was generated by chatGPT, and modified by myself to serve my needs. -->